services:
  db:
    image: postgres:16-alpine
    container_name: mpc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mpc
      POSTGRES_PASSWORD: mpc
      POSTGRES_DB: ma_petite_compagnie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
